engines:
  tailor:
    enabled: true

ratings:
  paths:
  - "**.swift"

exclude_paths:
    - MCSwiftLayoutTests
    - MCSwiftLayoutSample
    - Carthage
    - Source/Pods
    - data
    - scripts
    