include:
    - PinLayout

exclude:
    - PinLayoutTests
    - MCSwiftLayoutSample
    - Carthage
    - Source/Pods
    - data
    - scripts

except:
    - trailing-whitespace
    - brace-style
    - function-whitespace
    - terminating-semicolon