language: objective-c
osx_image: xcode8.3
# xcode_project: PinLayout.xcodeproj
# xcode_scheme: PinLayout
xcode_sdk: iphonesimulator9.3
env:
  - TARGET=ios
#  - TARGET=tvos
global: 
before_install:
  # iOS
  - |
    if [[ $TARGET = "ios" ]]; then
      brew outdated xctool || brew upgrade xctool;
      gem install xcpretty-travis-formatter;
      gem install cocoapods --pre --no-document --quiet;
      pod repo update --silent;
      pod install --repo-update;
    fi

  #- brew update
  #- brew install tailor
  # - gem install xcpretty-travis-formatter
  # - pod install --repo-update
  
script:
  # iOS
  - |
    if [[ $TARGET = "ios" ]]; then
      set -o pipefail &&
      xcodebuild -workspace PinLayout.xcworkspace -scheme "PinLayout" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' -enableCodeCoverage YES test | xcpretty -f `xcpretty-travis-formatter`
      set -o pipefail &&
      xcodebuild -workspace PinLayout.xcworkspace -scheme "PinLayoutTVOS" -sdk appletvsimulator10.2 -destination 'platform=tvOS Simulator,name=Apple TV 1080p' | xcpretty -f `xcpretty-travis-formatter`
      set -o pipefail &&
      xcodebuild -workspace PinLayout.xcworkspace -list
      set -o pipefail &&
      xcodebuild -workspace PinLayout.xcworkspace -scheme "PinLayoutSample" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty -f `xcpretty-travis-formatter`
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'PinLayout' -J 'PinLayoutTests'