language: objective-c
osx_image: xcode8.3
# xcode_project: PinLayout.xcodeproj
# xcode_scheme: PinLayout
xcode_sdk: iphonesimulator9.3

env:
  matrix:
    - TARGET=ios   SCHEME=PinLayout      SAMPLE_SCHEME=PinLayoutSample  SDK=iphonesimulator10.3   DESTINATION='platform=iOS Simulator,name=iPhone 6'
    - TARGET=tvos  SCHEME=PinLayoutTVOS  SAMPLE_SCHEME=None             SDK=appletvsimulator10.2  DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'

# script:
# - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR

# env:
  # - TARGET=ios
#  - TARGET=tvos
global: 

before_install:
  - |
    brew outdated xctool || brew upgrade xctool;
    gem install xcpretty-travis-formatter;
    gem install cocoapods --pre --no-document --quiet;
    pod repo update --silent;
    pod install --repo-update;
  
script:
  # iOS
  - |
    set -o pipefail &&
    xcodebuild -workspace PinLayout.xcworkspace -list
    set -o pipefail &&
    xcodebuild -workspace PinLayout.xcworkspace -scheme "$SCHEME" -sdk $SDK -destination $DESTINATION -enableCodeCoverage YES test | xcpretty -f `xcpretty-travis-formatter`

    if [[ $SAMPLE_SCHEME -ne "None" ]]; then
      set -o pipefail &&
      xcodebuild -workspace PinLayout.xcworkspace -scheme "$SAMPLE_SCHEME" -sdk $SDK -destination $DESTINATION -enableCodeCoverage YES test | xcpretty -f `xcpretty-travis-formatter`
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'PinLayout' -J 'PinLayoutTests'