language: objective-c
osx_image: xcode8
xcode_project: MCSwiftLayout.xcodeproj
xcode_scheme: MCSwiftLayout
xcode_sdk: iphonesimulator9.3
env:
  global: 
before_install:
  #- brew update
  #- brew install tailor
  - gem install xcpretty-travis-formatter
  - ./install-dependencies.sh
  
script: xcodebuild
  -project  MCSwiftLayout.xcodeproj
  -scheme "MCSwiftLayout"
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6'
  -enableCodeCoverage YES 
  test
 | xcpretty -f `xcpretty-travis-formatter`
