language: objective-c
osx_image: xcode8.3

env:
  matrix:
    - TARGET=ios   SCHEME=PinLayout        OPTIONS='-enableCodeCoverage YES test'  SDK=iphonesimulator10.3   DESTINATION='platform=iOS Simulator,name=iPhone 7'
#    - TRAGET=ios   SCHEME=PinLayoutSample  OPTIONS=''                              SDK=iphonesimulator10.3   DESTINATION='platform=iOS Simulator,name=iPhone 7'
#    - TARGET=tvos  SCHEME=PinLayoutTVOS    OPTIONS=''                              SDK=appletvsimulator10.2  DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'

before_install:
  - brew outdated xctool || brew upgrade xctool;
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --pre --no-document --quiet;
  - pod repo update --silent;
  - pod install --repo-update;
  
script:
  - set -o pipefail &&
    xcodebuild -workspace PinLayout.xcworkspace -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' $OPTIONS | xcpretty -f `xcpretty-travis-formatter`

#  - set -o pipefail &&
#    xcodebuild -workspace PinLayout.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" $OPTIONS | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - |
    if [[ $TARGET = "ios" ]]; then
      bash <(curl -s https://codecov.io/bash) -J 'PinLayout' -J 'PinLayoutTests'
    fi
